### ISSUE TITLE
Recovery Codes

### ISSUE THREAD

**Issue by therealssj** [ChristianRiesen/otp#10]
Any chance we could get a function to generate recovery codes?
Recovery codes are provided by Google also when you setup Two Factor Authentication for their apps.

**Comment by ChristianRiesen** [comment]
Those would be random "codes" with 6 or 8 digits usually. So you mean a convenience function to just create those? There is no specs otherwise for that.

**Comment by therealssj** [comment]
Yes. I think normally they are 9 digits long.

**Comment by ChristianRiesen** [comment]
I can add a solid random generator for those as a convenience function.

**Comment by therealssj** [comment]
Thank you for the awesome work!

**Comment by therealssj** [comment]
Any update on this?
If you haven't started maybe I can send in a pull request? ( wouldnt want work to overlap )

**Comment by ChristianRiesen** [comment]
It's added. Thanks for the suggestion :)

I did a bit of a clean up and bumped the version number one up. By the time you read this, it should be on packagist already.
