### ISSUE TITLE
Resynchronization of the HOTP Counter

### ISSUE THREAD

**Issue by therealssj** [ChristianRiesen/otp#11]
The HOTP standard defines the resynchronization algorithm which seems to be missing from this library.
This is a critical functionality which should be present as the end user might generate multiple otps and hence we lose track of the counter.

**Comment by ChristianRiesen** [comment]
To simplify discussion, here [the RFC](https://tools.ietf.org/html/rfc4226#section-7.4) about this:

> Although the server's counter value is only incremented after a
>    successful HOTP authentication, the counter on the token is
>    incremented every time a new HOTP is requested by the user.  Because
>    of this, the counter values on the server and on the token might be
>    out of synchronization.
> 
>    We RECOMMEND setting a look-ahead parameter s on the server, which
>    defines the size of the look-ahead window.  In a nutshell, the server
>    can recalculate the next s HOTP-server values, and check them against
>    the received HOTP client.
> 
>    Synchronization of counters in this scenario simply requires the
>    server to calculate the next HOTP values and determine if there is a
>    match.  Optionally, the system MAY require the user to send a
>    sequence of (say, 2, 3) HOTP values for resynchronization purpose,
>    since forging a sequence of consecutive HOTP values is even more
>    difficult than guessing a single HOTP value.
> 
>    The upper bound set by the parameter s ensures the server does not go
>    on checking HOTP values forever (causing a denial-of-service attack)
>    and also restricts the space of possible solutions for an attacker
>    trying to manufacture HOTP values. s SHOULD be set as low as
>    possible, while still ensuring that usability is not impacted.

I see where you are coming from, the question is how could the library be of service? You could generate them one by one from a known counter value and compare in user land code. If the Library does this, it would have to return the counter on which it hit pay-dirt at least, otherwise you wouldn't know where to resync. The "give 2 consecutive values" is even a bit trickier.

Please let me know what you think would work here or simply send a pull request if you like.

**Comment by therealssj** [comment]
I say it should be a built in ability in this library to make it whole.
Otherwise everyone who uses it will have to implement this whole synchronization part.

As for how, In totp check the third parameter is `timedrift` we can have something similar for hotp.
And yes it would need to return the counter on which it hits the correct code.

Let me know what you think. 
A bit busy today but will send the pull request asap depending whatever is settled here :)

**Comment by therealssj** [comment]
Pull request https://github.com/ChristianRiesen/otp/pull/12

**Comment by ChristianRiesen** [comment]
Merged. Making tag now. Thanks a lot!
