### ISSUE TITLE
README example is confusing

### ISSUE THREAD

**Issue by fkooman** [ChristianRiesen/otp#14]
In the README:

```
// Just to create a key for display (testing)
$key = $otp->totp($secret);
```

This should be:

```
$key = $otp->totp(Base32::decode($secret));
```

Took me a while to figure that one out :-)

**Comment by ChristianRiesen** [comment]
You are 100% correct. Thank you for the hint. I changed it and it's correct now on the README. Won't tag a new version for this though :)
