### ISSUE TITLE
OTP implicitly requires PHP 7

### ISSUE THREAD

**Issue by swichers** [ChristianRiesen/otp#21]
The composer.json requirement is PHP 5.4 or greater, but goes on to include either version 1 or 2 of https://github.com/paragonie/constant_time_encoding

Version 2 of constant_time_encoding requires PHP 7. This means composer can grab version 2 but the codebase can run on a lower PHP version.

I solved this for my project by explicitly requiring the 1.0 version

```
composer require paragonie/constant_time_encoding:^1.0
```

**Comment by ChristianRiesen** [comment]
That is by design, you can choose which one to use.

I will update it soonish and then have a new major version that requires PHP 7 completely, so that ambiguity is gone.
