### ISSUE TITLE
constant-time remainder

### ISSUE THREAD

**Issue by fkooman** [ChristianRiesen/otp#22]
I don't think the remainder (`%`) operator is constant-time, so it leaks a bit of information about the OTP:

https://github.com/ChristianRiesen/otp/blob/f29c9eb9f9a7117a9e9912dac2f474120061260d/src/Otp.php#L334

**Comment by ChristianRiesen** [comment]
This is used in the function to get the "human readable number". An attacker could only detect the time it takes to create this staying the same in the same window of opportunity. It's the implementer's burden to make sure an attacker could not trigger a repeated output over and over in a very narrow time window.

But, if you have a mitigation for this, please let me know, I'm always interested in improvements :) Until then I'm closing this issue.

**Comment by fkooman** [comment]
Fair enough.

I was thinking using something like `sprintf("%d", $foo)` but not sure if that would actually work or be any better...

**Comment by ChristianRiesen** [comment]
If you find one, I'm always happy to merge contributions :)
