### ISSUE TITLE
Don't use rand()

### ISSUE THREAD

**Issue by tomdxw** [ChristianRiesen/otp#3]
Bug is here: https://github.com/ChristianRiesen/otp/blob/7b1c92e964a440d3059c13cff2d18453ff2a2a4a/src/Otp/GoogleAuthenticator.php#L154

rand() isn't a CSPRNG - even the PHP team caution against treating it as such: http://php.net/rand#refsect1-function.rand-notes

**Comment by ChristianRiesen** [comment]
Thank you, fixed it now.
