### ISSUE TITLE
Composer now requires random_compat v99.99.99

### ISSUE THREAD

**Issue by chrisdeeming** [ChristianRiesen/otp#36]
Hey @ChristianRiesen 

I haven't yet looked into this for long enough to understand why, but the change in #32 appears to end up requiring password_compat v99.99.99.

I guess it's something to do with this?

https://github.com/paragonie/random_compat#version-99999

With that in mind, is this behaviour intended?

Chris

**Comment by chrisdeeming** [comment]
It's ok, I think I should learn to read properly. That's exactly what the change was for. Never mind!

**Comment by ChristianRiesen** [comment]
No problem @chrisdeeming 
The next version will not contain that anymore anyways.
